language: rust
dist: xenial
rust: nightly

before_script:
  - cargo update
  - rustup update

jobs:
  include:
    - stage: test
      script:
        - cargo test --all --all-features --verbose
    - stage: deploy-cargo
      script:
        - cd ./rabbithole
        - cargo publish --dry-run
        - cargo publish --token "$CARGO_TOKEN"
        - cd ../rabbithole-derive
        - cargo publish --dry-run
        -  cargo publish --token "$CARGO_TOKEN"
        - cd ../rabbithole-endpoint-actix
        - cargo publish --dry-run
        - cargo publish --token "$CARGO_TOKEN"
      if: tag IS present