[package]
name = "rabbithole-endpoint-actix"
version = "0.1.0"
authors = ["UkonnRa <ukonnra@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mock_gen"
path = "src/mock_gen.rs"

[dependencies]
futures-preview = { version = "=0.3.0-alpha.19", features = ["compat"] }
futures01 = { package = "futures", version = "~0.1" }
actix-web = "~1.0"
actix-service = "~0.4"

url = "~1.7"

serde = "~1.0"
serde_json = "~1.0"
uuid = "~0.8"
async-trait = "~0.1"
rand = "~0.7"

rabbithole = { path = "../rabbithole", features = ["unstable-vec-to-document"] }
rabbithole-derive = { path = "../rabbithole-derive" }