[package]
name = "rabbithole-endpoint-actix"
version = "0.1.0"
authors = ["UkonnRa <ukonnra@outlook.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "=0.3.0-alpha.19", features = ["compat"] }
futures01 = { package = "futures", version = "~0.1" }
actix-web = "~1.0"

url = "~1.7"

serde = "~1.0"
serde_json = "~1.0"
uuid = "~0.8"
async-trait = "~0.1"
rand = "~0.7"
config = "~0.9"

rabbithole = { path = "../rabbithole", features = ["unstable-vec-to-document"] }
rabbithole-derive = { path = "../rabbithole-derive" }